language: php
php:
  - 7.1.9
script:
  - phpunit --no-coverage indexTest.php
deploy:
  provider: heroku
  api_key:
    secure: AYSNNKxGWFY2CGFspHe6ifcq8WEvz36KLKRNCYjZ4Bhgeh/UnaWE7S+vwsGljwCpAw7CNZo6CdNn2F71LrJQzD4JHiakT0BSR/a4ABygXRBheCBDWHe27P2nlcLHbGbLzo6U8j21DaUVZV782c8nABid4kMJTWkB1yD1kH+CJxLt6WQ8H37+lEfjWEsy1KA/ZYURtYOeU8Thi2wq2zAfQM2gqN4HOvVRrmyepaFXEr6j43v9Y7KyfH78gnuKRPVVldTA4YLdMSpU5nsxw5zvX0B0LfWYnC2qR10bVJjENcnHmSfH3ro8hz99XePjsX9gnN37aji6SQTD/bWwA2fEaO019Lrbbr7MZDwhLoTDZlhHDqIY0ioNa0ZtcFsuYzFgWB/oYnEGDw5iXT8AtefBdEF3EUIWLgysEiSP9fvd9+2cGRVBJKG3dai/S/B6mXuxM0BrAvpX0q55+cmko09t6nY2AZYK7vUhSQeH8vED0MLFF7B+NkZKUd/riK9dIkDqlsifHcLL7YS98wgK/kfWM9/x84nMYlLIcnc2jAtqIsuqoM1rE8Ho1FhITJPa4/kL3/fTNPLmPHywLd8L7h/kCnO00bSziSyMmxXNQWgwOrqKC8c7zG1HVxI1tJobe4WL5Fe2m3HsNOJpNhIjiJryEEOoDxS5rGl6w+JvkjDX3dY=
  app:
    master: devops-essense